### PR TITLE
Simplified `syslog::unix()` by using `UnixDatagram::connect()` (fixes #1)

### LINKED ISSUE #1: Is tempfile needed?
Hi,

I wonder why do you create temporary path and bind to it for connecting to unix datagram socket? (https://github.com/Geal/rust-syslog/blob/master/src/lib.rs#L123)

It seems that competitor `sysly` doesn't do that (https://github.com/softprops/sysly/blob/master/src/lib.rs#L154)

### PR DESCRIPTION
**Pull request by tailhook**
The only thing I'm not sure of, is whether next `connect()` after error works for all platforms. I've tested only on linux.

### CODE REVIEW

**Comment by tailhook** [comment]
@Geal did you have a chance to look at this PR? Anything wrong with it?

**Comment by Geal** [comment]
It looks good, just let me find the time to test it. I was stuck with client work these past days, I might be able to look at it on Wednesday (or whenever I get bored of JS and do some Rust for distraction).

**Comment by tailhook** [comment]
@Geal, did you have a chance to test the pull request?

**Comment by Geal** [comment]
It's all good, thanks!

**Pull request merged**
