### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by bkchr**
Fixes: https://github.com/Geal/rust-syslog/issues/27

### CODE REVIEW

**Comment by bkchr** [comment]
I think that somehow broke something. My test machine logs everything with `kern_emerg` and almost everything in a new line. I will need to further debug this..

**Comment by bkchr** [comment]
Okay, I could fix the problem. It was not my fault, it was already present. We should create some tests to cover all this.
@Geal are you willing to merge this?

**Comment by daboross** [comment]
IIRC `format!()` is really just `write!()` to a allocated string which then can be written with. This has a small performance penalty, and also seems a bit like a workaround rather than an actual fix - do you think it'd be alright to separate that bugfix out into a separate PR for separate review/merging?

Both `format!()` / `.write()` and `write!()` will end up calling the exact same methods with the exact same bytes; the only difference I know of is that `format!()` allows batching things together. If `format!()` fixes the bug, it sounds like the actual bug is in `LoggerBackend`'s `Write` implementation, which doesn't treat bytes equally.

I'm all for upgrading the dependencies, but it would be nice to be able to discuss and fix the bugfix separately from this main change.

**Comment by bkchr** [comment]
Yeah, I know that `format!` and `write!` should go almost the same path. The only difference I can imagine is that `write!` writes byte by byte or something similar and the syslog implementation reads it byte by byte. On my test machine I saw that each log message got split across several log messages.
I can create a different pull request, just with "the fix"/hack in it. I'm open to a better solution, but currently I don't have any :/

**Comment by Geal** [comment]
Hello,

Thank you for taking care of this.
First things first: please keep the changes minimal, avoid cosmetic changes
and reindentation. I'd be willing to merge it but I do not have the time to
check all the indentation changes and see if something else changed.

The fixes to kern_emerg and format! usage can go in other pull requests

On Feb 28, 2018 09:31, "Bastian Köcher" <notifications@github.com> wrote:

Yeah, I know that format! and write! should go almost the same path. The
only difference I can imagine is that write! writes byte by byte or
something similar and the syslog implementation reads it byte by byte. On
my test machine I saw that each log message got split across several log
messages.
I can create a different pull request, just with "the fix"/hack in it. I'm
open to a better solution, but currently I don't have any :/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Geal/rust-syslog/pull/28#issuecomment-369159238>, or mute
the thread

**Comment by bkchr** [comment]
@Geal yeah, I already created a new pull request. And yeah, I run rustfmt, but I created a separate commit for this, so the real changes can be seen easily.

**Comment by oherrala** [comment]
This PR also fixes #32.

**Comment by bkchr** [comment]
@Geal any chance that this could be merged?
I also would be open to help you maintaining this crate.

**Comment by Geal** [comment]
Hello,

I merged all the commits except the rustfmt one. I'll see if I can make a format pass before the release.
@bkchr I'll give you commit rights to the repo, thanks for your help :)

**Pull request closed without merging**
